<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ComputeSharp" Version="3.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\UI\*.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
